require:
  - rubocop-rspec
  - rubocop-performance
AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/MethodLength:
  IgnoredMethods: ['to_h']
